applications/web/blog/urls.py
from django.conf.urls import patterns, url

from .views import ArticlesListView, ArticleDetailView, CategoryDetailView#, CategoriesListView


urlpatterns = patterns('',
    url(r'^categoria/(?P<slug>.*)/$', CategoryDetailView.as_view(), name='category_detail'),
    url(r'^$', ArticlesListView.as_view(), name="articles_list"),
    url(r'^(?P<slug>.*)/$', ArticleDetailView.as_view(), name='articles_detail'),
    #url(r'^$', CategoriesListView.as_view(), name="categories_list"),
    #url(r'^(?P<slug>.*)/$', CategoryDetailView.as_view(), name='category_detail'),
)

applications/web/contacts/urls.py
from django.conf.urls import patterns, url

from .views import ContactFormView, ContactFormAjaxView


urlpatterns = patterns('',
    url(r'^multi_form/$', ContactFormAjaxView.as_view(), name='multi_form'),
    url(r'^$', ContactFormView.as_view(), name='contact_form'),
)

applications/web/sumicorpcommx/urls.py
from __future__ import print_function
from cms.sitemaps import CMSSitemap
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls import patterns, url

#sitemap
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from cms_extensions.CMSSitemap import CMSSitemap_custom

from blog.models import Article, Category
from products.models import Product
from industries.models import Industry
# from services.models import Service
# from faq.models import Sections, Question

admin.autodiscover()

articles_dict = {
    'queryset': Article.objects.all(),
    'date_field': 'publish_date',
}

categories_dic = {
    'queryset': Category.objects.all(),
    'date_field': 'publish_date',
}
products_dic = {
    'queryset': Product.objects.all(),
    'date_field': 'publish_date',
}
industries_dic = {
    'queryset': Industry.objects.all(),
    'date_field': 'publish_date',
}

#services_dic = {
#    'queryset': Service.objects.all(),
#    'date_field': 'publish_date',   
#}

#sections_dic = {
#    'queryset': Sections.objects.all(),
#    'date_field': 'create_date'
#}

#questions_dic = {
#    'queryset': Question.objects.all(),
#    'date_field': 'create_date'
#}

sitemaps = {
    'flatpages': CMSSitemap_custom,
    'blog': GenericSitemap(articles_dict, priority=0.6),
    'categorias': GenericSitemap(categories_dic, priority=0.6),
    'producto': GenericSitemap(products_dic, priority=0.6),
    'industria': GenericSitemap(industries_dic, priority=0.6),
    #'servicios': GenericSitemap(services_dic, priority=0.6),
    #'preguntas': GenericSitemap(questions_dic, priority=0.6),
    #'secciones': GenericSitemap(sections_dic, priority=0.6),
}

urlpatterns = i18n_patterns('',
    url(r'^uQwBke/', include(admin.site.urls)),  # NOQA
   
    #url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^', include('cms.urls')),
)
urlpatterns += patterns('',
	url(r'^redactor/', include('redactor.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

applications/web/contacts/models.py
import smtplib

from django.db import models
from django.utils import timezone
from django.template.loader import render_to_string

from cms.models import CMSPlugin


class Contact(models.Model):
    COUNTRIES = (('MX','Mexico'),('EX','Otro'),)
    name = models.CharField(
        u'Nombre Completo',
        blank=True,
        default='',
        help_text=u'Nombre Completo',
        max_length=256,
    )
    company = models.CharField(
        u'Empresa u Organizacion',
        blank=True,
        default='',
        help_text=u'Nombre de su Empresa',
        max_length=128,
    )
    email = models.EmailField(
        u'Email',
        blank=True,
        default='',
        error_messages={'invalid': 'Introduzca un email valido'},
        help_text=u'Su Email',
        max_length=128,
    )
    country = models.CharField(
        u'Pais',
        max_length=64,
        choices=COUNTRIES,
        blank=True
    )
    telephone = models.CharField(
        u'Telefono',
        blank=True,
        default='',
        help_text=u'Introduzca su Numero Telefonico',
        max_length=32,
    )
    comments = models.TextField(
        u'Mensaje',
        blank=True,
        default='',
        help_text=u'Aqui va su mensaje.',
    )
    send_to = models.CharField(
        u'Enviado desde:',
        blank=True,
        default='',
        help_text='Link donde se mando el correo',
        max_length=256,
    )
    contact_date = models.DateTimeField(
        u'contact date',
        blank=True,
        default=timezone.now,
        help_text=u'Cuando se realizo este contacto.',
    )

    def send_notification_email(self):
        email_subject = render_to_string('contacts/notification-subject.txt', {
            'contact': self,
        })

        email_body = render_to_string('contacts/notification-body.txt', {
            'contact': self,
        })
        #print email_subject;
        #print email_body;
        try:
            #fromaddr = 'sumicorpdemexico@gmail.com'
            fromaddr = 'info@sumicorp.com.mx'
            toaddrs  = ['edson@evolutiva.mx', 'ev.sumicorp@gmail.com', 'jflores@sumicorp.com.mx', 'btorres@sumicorp.com.mx', 'eflores@sumicorp.com.mx']
            subject = "Subject: " + email_subject
            #msg = "\r\n".join([ "From: sumicorpdemexico@gmail.com", "To: " + ", ".join(toaddrs), subject, "", email_body ])
            msg = "\r\n".join([ "From: info@sumicorp.com.mx", "To: " + ", ".join(toaddrs), subject, "", email_body ])
            #username = 'sumicorpdemexico@gmail.com'
            username = 'info@sumicorp.com.mx'
            #password = 'SK6b9PeXb743V6c'
            password = 'sumicorp'
            #server = smtplib.SMTP('smtp.gmail.com:587')
            server = smtplib.SMTP('smtp.sumicorp.com.mx:25')
            server.ehlo()
            #server.starttls()
            server.login(username,password)
            server.sendmail(fromaddr, toaddrs, msg)
            server.quit()

        except Exception:
            # If NOT in DEBUG (development) mode, we silently ignore any
            # exceptions to avoid interrupting capture of the submitter's
            # details. If in DEBUG mode, then raise the error so we can
            # troubleshoot.
            if (settings.DEBUG):
                raise

    def save(self, *args, **kwargs):
        if not self.pk:
            try:
                self.send_notification_email()
            except:
                pass
        super(Contact, self).save(*args, **kwargs)

    def __str__(self):
        return '%s (%s)' % (self.name, str(self.contact_date), )


class ContactPluginModel(CMSPlugin):
    title = models.CharField(
        u'title',
        blank=True,
        help_text=u'Opcional. Titulo del Widget',
        max_length=64,
    )

applications/web/contacts/forms.py
from django import forms
from django.forms import ModelForm

from .models import Contact


class ContactBaseForm(ModelForm):
    class Meta:
        abstract = True

    required_fields = []

    def __init__(self, *args, **kwargs):
        super(ContactBaseForm, self).__init__(*args, **kwargs)

        for field in self.required_fields:
            self.fields[field].required = True


class ContactForm(ContactBaseForm):
    class Meta:
        model = Contact
        fields = [
            'name', 'company', 'email', 'country',
            'telephone', 'comments',
             'acepto_aviso_de_privacidad', 'send_to',
        ]

    acepto_aviso_de_privacidad = forms.BooleanField()
    send_to = forms.CharField(widget = forms.HiddenInput())

    required_fields = ['name', 'email', 'company', 'telephone', 'comments', 'acepto_aviso_de_privacidad', 'country', 'send_to',]

    def clean(self):
        cleaned_data = super(ContactForm, self).clean()
        privacyterms = cleaned_data.get('acepto_aviso_de_privacidad')

        if privacyterms is not True:
            raise forms.ValidationError(u'Debe aceptar los terminos de privacidad')

        return cleaned_data


class ContactAjaxForm(ContactBaseForm):
    class Meta:
        model = Contact
        fields = ['name', 'company', 'telephone', 'email', 'comments', 'send_to' ]

    send_to = forms.CharField(widget = forms.HiddenInput())

    required_fields = ['name', 'company', 'telephone', 'email', 'comments', 'send_to' ]


class ContactAjaxFormModal(ContactBaseForm):
    class Meta:
        model = Contact
        fields = ['name', 'company', 'country','telephone', 'email', 'comments', 'send_to',]

    send_to = forms.CharField(widget = forms.HiddenInput())

    required_fields = ['name', 'company', 'country','telephone', 'email', 'comments', 'send_to',]

applications/web/contacts/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import FormView
from django.shortcuts import get_object_or_404

from cms.models.pagemodel import Page

from .forms import ContactForm, ContactAjaxForm


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'contacts/contact_form.html'

    def get_success_url(self):
        page = get_object_or_404(
            Page,
            reverse_id="contact_form_submission",
            publisher_is_draft=False
        )
        return page.get_absolute_url()

    def form_valid(self, form):
        self.object = form.save()
        return super(ContactFormView, self).form_valid(form)


class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """

    def render_to_json_response(self, context, **response_kwargs):
        data = json.dumps(context)
        response_kwargs['content_type'] = 'application/json'
        return HttpResponse(data, **response_kwargs)

    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return self.render_to_json_response(form.errors)  # , status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return self.render_to_json_response(data)
        else:
            return response


class ContactFormAjaxView(AjaxableResponseMixin, FormView):
    form_class = ContactAjaxForm
    http_method_names = [u'post']
    template_name = 'contacts/contact_widget.html'

    def get_success_url(self):
        return self.request.path

    def form_valid(self, form):
        self.object = form.save(commit=True)
        return super(ContactFormAjaxView, self).form_valid(form)

applications/web/contacts/templates/contacts/contact_form.html
{% extends CMS_TEMPLATE %}
{% load cms_tags sekizai_tags staticfiles i18n widget_tweaks %}

{% block body_classes %}{{ block.super }} contact-form {% endblock %}

{% block app_content %}
{% get_current_language as LANGUAGE_CODE %}
<!-- Current language: {{ LANGUAGE_CODE }} -->
<input type="hidden" id='form-contact-app-lang' value="{{ LANGUAGE_CODE }}">

<form method="post" role="form" id="form-contact-app">
	{% csrf_token %}

	{% for visible in form.visible_fields %}
		{% if forloop.counter0|divisibleby:"2" %} <div class="row"> {% endif %}
			<div class="col-lg-6">
				<div class="form-group {{ visible.css_classes }}">
					{% trans visible.label_tag %}
					{{ visible|add_class:"form-control"}}
					{% for error in visible.errors %}
						<span class="text-danger">{{ error }}</span>
					{% empty %}
						<!-- <span class="help-block">{{ visible.help_text }}</span> -->
					{% endfor %}
				</div>
			</div>
		{% if forloop.last or forloop.counter|divisibleby:"2" %} </div> {% endif %}
	{% endfor %}
	{% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
	<div class="row">
		<div class="col-lg-6"></div>
		<div class="col-lg-6">
			<button type="submit" id="form-contact-app-submt" class="btn btn-primary">Submit</button>
		</div>
	</div>
</form>
{% endblock app_content %}

{% block custom_js %}
<script>
	$(document).ready(function(){
		//Clean elements
		var app_lang = $('#form-contact-app-lang').val(),
		form_contact_app_labels = {
			'id_name' : {
				'lbl':'Full Name:',
				'pch':'Name'
			},
			'id_comments': {
				'lbl':'Message:',
				'pch':'Insert message here.'
			},
			'id_company': {
				'lbl':'Company:',
				'pch':'Company'
			},
			'id_telephone': {
				'lbl':'Telephone:',
				'pch':'Telephone number'
			},
			'id_email': {
				'lbl':'Email:',
				'pch':'Email'
			},
			'id_country': {
				'lbl':'Country',
				'pch':'Country'
			}
		},
		privacy_terms = {
			'es':{
				'lbl':'Acepto el <a href="/es/aviso-de-privacidad">Aviso de Privacidad</a>',
			},
			'en':{
				'lbl':'I accept the <a href="/en/privacy-notice/">Privacy Notice</a>',
			},
		},
		pt_lbl = privacy_terms.es.lbl;

		if(app_lang == 'en'){
			$.each( form_contact_app_labels, function( key, value ) {
			  	$("#form-contact-app label[for='"+key+"']").html(value.lbl);
			  	$("#form-contact-app #"+key).attr('placeholder', value.pch);
			  	$("#form-contact-app #"+key).attr('required', 'required');
			});
			pt_lbl = privacy_terms.en.lbl;
		}

		$('#form-contact-app #id_acepto_aviso_de_privacidad').remove();
		$('#form-contact-app #form-contact-app-submt').remove();
		$('#form-contact-app #id_comments').attr('rows', '3')

		//link de donde se manda el correo
		$('#form-contact-app #id_send_to').val(document.URL);

		//validacion de seleccion de pais
		$('#form-contact-app #id_telephone').prop("disabled", true);
		$('#form-contact-app #id_country').change(function(){
			var country_val = $('#form-contact-app #id_country').val();
			if (country_val == '' || country_val == undefined) {
				$('#form-contact-app #id_telephone').prop("disabled", true);
			} else {
				$('#form-contact-app #id_telephone').prop("disabled", false);
			}
		})

		//insert elements

		//masked input
		//$('#form-contact-app #id_country').val('EX')
		$('#form-contact-app #id_country').change(function(){
			var elval = $('#form-contact-app #id_country').val();
			var clear_telephone = $("#form-contact-app #id_telephone").val("");
			var html_number_code = " <span id='number_code' style='font-size: 10px;'> {% if LANGUAGE_CODE == 'en' %} Country code <b>+</b> City code <b>+</b> Phone number {% else %} Código País <b>+</b> Código Ciudad <b>+</b> Número Telefónico {% endif %} </span> ";
			var delete_number_code = $("#form-contact-app #number_code").remove();

			if(elval=='MX'){ 
				$("#form-contact-app #id_telephone").mask("(***) ***-****", {placeholder:"(***) ***-****"}); 
				delete_number_code;
				clear_telephone;
			}
			else if (elval=='EX'){
				$("#form-contact-app #id_telephone").mask("*** + **** + ********", {placeholder:"*** + **** + ********"});
				clear_telephone;
				//place holder label que indica la forma de mandar el telefono si es un país extranjero
				$("#form-contact-app #id_telephone").html(html_number_code).parent().append(html_number_code);
				// Country code + City code + Phone number
			}
			else{
				delete_number_code;
				clear_telephone; 
			}
		})


		var html = ' <input type="checkbox" name="acepto_aviso_de_privacidad"></input id="id_acepto_aviso_de_privacidad" required="required"> ' + pt_lbl;
		var sbmt_frm_txt = (app_lang == 'en') ? 'Submit' : 'Enviar'
		$("#form-contact-app label[for='id_acepto_aviso_de_privacidad']").html(html).parent().append('<button type="submit" class="btn btn-primary">'+sbmt_frm_txt+'</button>')
	})
</script>
{% endblock custom_js %}

applications/web/contacts/templates/contacts/contact_widget.html
{% load cms_tags sekizai_tags staticfiles i18n widget_tweaks %}

{% addtoblock "custom_js_tmp" %}<script src="{% static 'js/quick.contact.widget.js' %}"></script>{% endaddtoblock %}

{% get_current_language as LANGUAGE_CODE %}
<!-- Current language: {{ LANGUAGE_CODE }} -->
<input type="hidden" id='form-contact-widget-lang' value="{{ LANGUAGE_CODE }}">

<form role="form" id="contact-plugin-form" class="contacts-plugin" method="post" action="{{ form_action }}">
    {% csrf_token %}

    {% for visible in form.visible_fields %}
    <div class="form-group">
      {{ visible|add_class:"form-control"}}
      <span class="error" style="color:#FC7474"></span>
    </div>
    {% endfor %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

  	{% if LANGUAGE_CODE == 'en' %}
  		<a href='#' id="submit-contact-plugin-form" class="btn btn-primary">Submit</a>
  	{% else %}
  		<a href='#' id="submit-contact-plugin-form" class="btn btn-primary">Enviar</a>
  	{% endif %}
</form>

{% if LANGUAGE_CODE == 'en' %}
	<div class="success" style="display:none; color:white;">Thank you!, We contact you as soon as possible.</div>
{% else %}
	<div class="success" style="display:none; color:white;">¡Gracias!, nos pondremos en contacto con usted en breve.</div>
{% endif %}

applications/web/contacts/templates/contacts/contact_widget_modal.html
{% load cms_tags sekizai_tags staticfiles i18n widget_tweaks %}

{% addtoblock "custom_js_tmp" %}<script src="{% static 'js/quick.contact.modal.widget.js' %}"></script>{% endaddtoblock %}


{% get_current_language as LANGUAGE_CODE %}
<!-- Current language: {{ LANGUAGE_CODE }} -->
<input type="hidden" id='form-contact-modal-widget-lang' value="{{ LANGUAGE_CODE }}">

<form role="form" id="contact-plugin-modal-form" class="contacts-plugin" method="post" action="{{ form_action }}">
    {% csrf_token %}

    {% for visible in form.visible_fields %}
    <div class="form-group">
    	<label></label>
      	{{ visible|add_class:"form-control"}}
      	<span class="error" style="color:#FC7474"></span>
    </div>
    {% endfor %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
	<div class="checkbox">
	  	<label>
	  		{% if LANGUAGE_CODE == 'en' %}
	  			<input type="checkbox" required="required"> I accept the <a href="/en/privacy-notice/">Privacy Notice</a>
	  		{% else %}
	  			<input type="checkbox" required="required"> Acepto el <a href="/es/aviso-de-privacidad">Aviso de Privacidad</a>
	  		{% endif %}
	  	</label>
	</div>
</form>

{% if LANGUAGE_CODE == 'en' %}
	<div class="success" style="display:none;">Thank you!, We contact you as soon as possible.</div>
{% else %}
	<div class="success" style="display:none;">¡Gracias!, nos pondremos en contacto con usted en breve.</div>
{% endif %}